### PR TITLE
Container Working Group HPC Survey

### PR DESCRIPTION
**Pull request by kniec**

### CODE REVIEW

**Comment by kniec** [comment]
hmm. can I not squash the commits in a PR?

**Comment by vsoch** [comment]
yes we definitely can - if you can't do it from the command line we can here:

image

**Comment by kniec** [comment]
ah, awesome - I am not seeing the squash options. :)

**Comment by kniec** [comment]
I thought it will be shown when create a new PR. Do you want to use this PR or #36 ?

**Comment by vsoch** [comment]
Either one would work! Do you have a preference, and are you ready to squash? Do you want me to start the ball rolling on figuring out the IRB exemption?

**Comment by kniec** [comment]
please do squash and get the ball rolling. I'll ping folks internally as well to have a broader reach.

**Comment by vsoch** [comment]
Done! It's a holiday over here but I'll get some emails out today anyway!

**Pull request merged**
