### PR TITLE
Updated Singularity project page

### PR DESCRIPTION
**Pull request by gmkurtzer**
* Cleaned up unecessary content
  * Singularity CRI: project abondoned
  * Library API: not OCI
  * Singularity Registry: not OCI (correct me if I'm wrong)
* Project Ideas: No need to create a Singularity registry, it
  works with all existing OCI compliant registries today.

### CODE REVIEW

**Comment by vsoch** [comment]
It’s ok if the Singularity CRI project was abandoned, it’s part of the story and this document can and should include historical decisions. 

And why did you remove my registry projects? They are also part of the story.

If you’d like to write the paragraph for those things, it would be great! Otherwise I can make a suggestion, although I only know about what others have.

My statements about the project that you entirely deleted were not incorrect - the original write did not have OCI in mind, nor did the subsequent library.  This currently reads like an advertisement for Singularity instead of a discussion of its trajectory and that’s not the goal of the write up.

**Review by vsoch — CHANGES_REQUESTED** [review]
Please add back the details that you removed, and frame the write up to be less an advertisement and more a history of the trajectory of the project and successes and challenges with OCI.

**Comment by gmkurtzer** [comment]
It is clear that I misunderstood, my apologies. Please disregard my PR.

**Comment by vsoch** [comment]
No worries! A lot of the ideas or projects are going to leverage some of the features you mention about Singularity, so please keep an eye on the space.

**Pull request closed without merging**
